name: Deploy to Firebase
on:
  push:
    branches:
      - main
      - master

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Dependencies & Build
        run: |
          npm ci
          cd functions && npm ci && cd ..
          npm run build

      - name: Authenticate to GCP / Firebase
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_HCTCPLAYER }}'

      - name: Deploy Hosting and Functions to Firebase
        run: |
          npx firebase-tools deploy --only hosting,functions --project hctcplayer
